config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  concern :auditable do
    member { get :audit }
  end

  concern :receivable do
    member { get :receive }
  end

  concern :has_items do
    member do
      post :upload
      get :new_items
    end
  end

  concern :has_label do
    member do
      get :label
      get :label_preview
    end
  end

  get 'home',        to: 'dashboard#home'
  get 'export',      to: 'dashboard#export'

  get 'billing/due',    to: 'billing#due'
  get 'billing/report', to: 'billing#report'
  get 'billing/export', to: 'billing#export'

  resources :dashboard, only: [] do
    collection do
      post :export
    end
  end

  resources :categories
  resources :customers do
    member do
      get :billing
      get 'sku_infos(/:scope)', to: "customers#sku_infos"

      get :order_history
      get :sku_history
    end
  end

  resources :orders, concerns: [:has_label] do
    collection do
      get :outstanding
    end
    member do
      get :pick_list
      get :invoice
      get :invoice_preview

      get 'ship_list(/:preview)', to: 'orders#ship_list', as: :ship_list
      get :ship_list_preview

      get :confirmation
      get :confirmation_preview

      get :shipping_label_preview

      post :mark_as_billed
    end

    resources :order_items, only: [:index, :new, :create], path: :items do
    end
  end

  resources :order_items, only: [:update, :edit, :show, :destroy, :index] do
    member do
      get   :split
      patch :split
      post :mark_as_delivered
      post :mark_has_issue
      post :confirm_picked
    end
  end

  resources :order_deposits do
  end

  resources :order_payments do
    resources :order_payment_items, except: [:destroy], path: :items
  end

  resources :order_payment_items do
  end

  resources :pre_orders, concerns: [:has_items, :auditable] do
    resources :pre_order_items, except: [:destroy], path: :items

    member do
      post :create_order
      post :resend_confirmation

      get :confirmation
      get :confirmation_preview
    end

  end

  resources :pre_order_codes
  resources :pre_order_items, only: [:destroy, :show], concerns: [:auditable] do
    collection do
      get :outstanding
    end
  end

  resources :prospects

  resources :purchase_orders, concerns: [:has_label, :has_items, :auditable, :receivable] do
    resources :purchase_order_items, except: [:destroy], path: :items
  end

  resources :purchase_order_items, only: [:index, :destroy, :update, :edit, :show], concerns: [:has_label, :receivable] do
    member do
      post :print
    end
  end

  resources :suppliers

  resources :sku_classes

  resources :sku_cust_infos

  resources :skus, concerns: [:auditable, :has_label, :receivable] do
    collection do
      get  :export
      get  :lookup
      put  :search
      post :search

      get :with_issues
    end

    member do
      post :duplicate
      get :po_history
      post :resolve_issue
      post :mark_has_issue
    end
  end

  resources :sku_po_histories, only: [:index]

  resources :tax_jurisdictions
  resources :vendors

  scope 'receive' do
    get 'by_sku', to: 'receiving#receive'
    get 'by_po',  to: 'receiving#receive'
  end

  get 'inventory', to: 'inventory#export'

  post 'scan', to: 'scans#post'
  resources :inventory_scan_operations, only: [:index, :show]

  mount Blazer::Engine, at: "blazer"

  root to: 'dashboard#home'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include DefaultCrudController

  resource_scope -> { Table.all }

  on :export, redirect: -> { export_path }

  def home
  end

  def export
    if request.get?
      DbExportService.export do |zipfile|
        send_data zipfile.data, filename: export_filename
      end
    else
      self.resource = Table.first
      respond_with_success resource, action_name
    end
  end

  private

  def export_filename
    "audit_data_export_#{Time.current.to_s(:number)}.zip"
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/export.js.erb
flashToast(<%= raw flash.to_json %>)
window.location.href = '/export'

app/views/dashboard/home.html.haml
.content
  .container-fluid
    .row
      .col-12.col-sm-6.col-md-3
        = link_to orders_path(scope: :outstanding) do
          .info-box.mb-3
            %span.info-box-icon.bg-warning.elevation-1
              = fa_icon 'star'
            .info-box-content
              %span.info-box-text Outstanding Orders
              %span.info-box-number= Order.outstanding.count

      .col-12.col-sm-6.col-md-3
        = link_to orders_path(scope: :awaiting_confirmation) do
          .info-box
            %span.info-box-icon.bg-info.elevation-1
              = fa_icon 'star'
            .info-box-content
              %span.info-box-text Orders Awaiting Confirmation
              %span.info-box-number= Order.awaiting_confirmation.count

      .clearfix.hidden-md-up

      .col-12.col-sm-6.col-md-3
        = link_to pre_orders_path(scope: :awaiting_analysis) do
          .info-box.mb-3
            %span.info-box-icon.bg-danger.elevation-1
              = fa_icon 'star'
            .info-box-content
              %span.info-box-text Pre-Orders Awaiting Analysis
              %span.info-box-number= PreOrder.awaiting_analysis.count

      .col-12.col-sm-6.col-md-3
        = link_to purchase_orders_path(scope: :outstanding) do
          .info-box.mb-3
            %span.info-box-icon.bg-success.elevation-1
              = fa_icon 'shopping-cart'
            .info-box-content
              %span.info-box-text POs Outstanding
              %span.info-box-number= PurchaseOrder.outstanding.count

    .row
      .col-lg-6
        = lte_card title: 'Order Volume by Week', tools: :maximize do |tools|
          - content_for tools do
            %a.btn.btn-primary.btn-tool{:href => orders_path} Go to Orders
          = line_chart Order.group_by_week(:orderdate).count
      .col-lg-6
        = lte_card title: 'Pre-Order Volume by Week', tools: [:collapse, :maximize] do |tools|
          - content_for tools do
            %a.btn.btn-primary.btn-tool{:href => pre_orders_path} Go to Pre-Orders
          = line_chart PreOrder.group_by_week(:preorderdate).count
    .row
      .col-lg-6
        = lte_card title: 'Credit Card Billing Volume (Prev 30 days)' do
          = line_chart Order.where("orderccdate > ?", 30.days.ago).group_by_day(:orderccdate).count