config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  concern :auditable do
    member { get :audit }
  end

  concern :receivable do
    member { get :receive }
  end

  concern :has_items do
    member do
      post :upload
      get :new_items
    end
  end

  concern :has_label do
    member do
      get :label
      get :label_preview
    end
  end

  get 'home',        to: 'dashboard#home'
  get 'export',      to: 'dashboard#export'

  get 'billing/due',    to: 'billing#due'
  get 'billing/report', to: 'billing#report'
  get 'billing/export', to: 'billing#export'

  resources :dashboard, only: [] do
    collection do
      post :export
    end
  end

  resources :categories
  resources :customers do
    member do
      get :billing
      get 'sku_infos(/:scope)', to: "customers#sku_infos"

      get :order_history
      get :sku_history
    end
  end

  resources :orders, concerns: [:has_label] do
    collection do
      get :outstanding
    end
    member do
      get :pick_list
      get :invoice
      get :invoice_preview

      get 'ship_list(/:preview)', to: 'orders#ship_list', as: :ship_list
      get :ship_list_preview

      get :confirmation
      get :confirmation_preview

      get :shipping_label_preview

      post :mark_as_billed
    end

    resources :order_items, only: [:index, :new, :create], path: :items do
    end
  end

  resources :order_items, only: [:update, :edit, :show, :destroy, :index] do
    member do
      get   :split
      patch :split
      post :mark_as_delivered
      post :mark_has_issue
      post :confirm_picked
    end
  end

  resources :order_deposits do
  end

  resources :order_payments do
    resources :order_payment_items, except: [:destroy], path: :items
  end

  resources :order_payment_items do
  end

  resources :pre_orders, concerns: [:has_items, :auditable] do
    resources :pre_order_items, except: [:destroy], path: :items

    member do
      post :create_order
      post :resend_confirmation

      get :confirmation
      get :confirmation_preview
    end

  end

  resources :pre_order_codes
  resources :pre_order_items, only: [:destroy, :show], concerns: [:auditable] do
    collection do
      get :outstanding
    end
  end

  resources :prospects

  resources :purchase_orders, concerns: [:has_label, :has_items, :auditable, :receivable] do
    resources :purchase_order_items, except: [:destroy], path: :items
  end

  resources :purchase_order_items, only: [:index, :destroy, :update, :edit, :show], concerns: [:has_label, :receivable] do
    member do
      post :print
    end
  end

  resources :suppliers

  resources :sku_classes

  resources :sku_cust_infos

  resources :skus, concerns: [:auditable, :has_label, :receivable] do
    collection do
      get  :export
      get  :lookup
      put  :search
      post :search

      get :with_issues
    end

    member do
      post :duplicate
      get :po_history
      post :resolve_issue
      post :mark_has_issue
    end
  end

  resources :sku_po_histories, only: [:index]

  resources :tax_jurisdictions
  resources :vendors

  scope 'receive' do
    get 'by_sku', to: 'receiving#receive'
    get 'by_po',  to: 'receiving#receive'
  end

  get 'inventory', to: 'inventory#export'

  post 'scan', to: 'scans#post'
  resources :inventory_scan_operations, only: [:index, :show]

  mount Blazer::Engine, at: "blazer"

  root to: 'dashboard#home'
end

app/models/pre_order.rb
class PreOrder < ApplicationRecord
  include HasBatch
  self.table_name  = 'tblpreorder'
  self.primary_key = 'preorderid'

  belongs_to :customer, foreign_key: :custid
  belongs_to :order,    foreign_key: :orderid,          optional: true
  belongs_to :vendor,   class_name: 'Supplier', foreign_key: :preordervendorid, optional: true

  belongs_to :supplier, class_name: 'Supplier', foreign_key: :splrid, optional: true

  has_many :items, -> { order(:preorderitemsid) }, class_name: 'PreOrderItem', foreign_key: :preorderid

  alias_attribute :notes, :preordernotes

  scope :analyzed,          -> { where.not(preorderanalysisdate: nil)}
  scope :confirmed,         -> { where.not(confirmationdate: nil)}
  scope :unconfirmed,       -> { where(confirmationdate: nil)}
  scope :checked,           -> { where.not(preordercheck: nil)}
  scope :not_checked,       -> { where(preordercheck: nil)}

  scope :awaiting_analysis, -> { confirmed.where(preorderanalysisdate: nil) }

  validates :preorderdate, presence: true

  after_save :set_order_confirmed_date

  has_batch_number :preorderbatch, date: :preorderdate, prefix: 'P-', attrs: 'customer.custname' do
    PreOrder
      .select(:preorderid, :preorderbatch)
      .where("DATE(preorderdate) = ?", self.preorderdate)
      .where(custid: self.custid)
      .order(:preorderbatch)
      .last&.preorderbatch
  end

  def create_order!
    return if order.present?

    transaction do
      create_order(
        orderdate:    self.preorderdate,
        custid:       self.custid,
        ordertaxrate: customer.custtaxrate
        )

      save && order_update!
    end
  end

  def set_order_confirmed_date
    return unless self.confirmationdate.present? &&
                  self.order.present?

    Rails.logger.debug "Setting order confirmationdate for #{self.order}"
    self.order.update(orderconfirmdate: self.confirmationdate)
  end

  # pricing calcs... probably should be calced on item edit and stored on the table row
  def ordersubtotal
    items.pluck(:orderpricetotal2).compact.sum
  end

  def ordertaxtotal
    ordersubtotal * customer.custtaxrate
  end

  def orderpricetotal
    ordersubtotal + ordertaxtotal
  end


  def create_order_items_sql
    qryPreOrderToOrder = <<~SQL
      INSERT INTO tblOrderItems (
        OrderID, SKUID, OrderQuant,
        OrderPricePer, OrderPriceTotal,
        OrderTaxRate,  OrderTaxTotal,
        OrderGrandTotal,
        POID
      )

      SELECT
        #{self.orderid} as orderid,
        tblPreOrderItems.skuid2,
        tblPreOrderItems.orderquant2,
        tblPreOrderItems.orderpriceper2,
        tblPreOrderItems.orderpricetotal2,
        tblCustomer.CustTaxRate,
        round((orderpricetotal2 * CustTaxRate)::numeric, 2) as tax_total,
        round((orderpricetotal2 + round((orderpricetotal2 * CustTaxRate)::numeric, 2))::numeric, 2) as OrderGrandTotal,
       CASE tblPreOrderItems.POID
       WHEN 0 THEN NULL
       ELSE tblPreOrderItems.POID
       END
      FROM tblPreOrderItems
      LEFT JOIN tblPreOrder ON tblPreOrder.PreOrderID = tblPreOrderItems.PreOrderID
      LEFT JOIN tblCustomer ON tblPreOrder.CustID     = tblCustomer.CustID
      WHERE tblPreOrderItems.PreOrderItemCode < 4
        AND tblPreOrderItems.PreOrderID = #{self.preorderid}
        AND tblPreOrderItems.OrderDate ISNULL
        AND tblPreOrderItems.skuid2 > 0
        AND tblPreOrderItems.poid > 0
    SQL
  end

  def update_pre_order_item_date_sql
    qryPreOrderOrderUpdateDate = <<~SQL
      UPDATE tblPreOrderItems
      SET   OrderDate = Now()
      WHERE OrderDate ISNULL
        AND PreOrderItemCode != 4
        AND PreOrderID = #{self.preorderid}
        AND poid > 0
    SQL
  end

  # def qryPreOrderOrderDateUpdate
  #   qryPreOrderOrderDateUpdate = <<~SQL
  #     UPDATE tblPreOrder
  #     LEFT JOIN tblOrder ON tblPreOrder.OrderID = tblOrder.OrderID
  #     SET tblPreOrder.OrderCreateDate = Now(),
  #         tblOrder.PreOrderCompleteDate = Now()
  #     WHERE tblPreOrder.PreOrderID = #{self.preorderid} [Forms]![frmPreOrder]![txtPreOrderID])
  #       AND (([Forms]![frmPreOrder]![txtPreOrderCompleteCheck])=0))
  #   SQL
  # end

  def pre_order_complete_check
    items.map(&:incomplete?)
  end

  def pre_order_complete?
    pre_order_complete_check.none?
  end

  def order_update!
    return unless order.present?

    transaction do
      # create order items
      PreOrder.connection.execute create_order_items_sql

      # update dates on pre-order items
      PreOrder.connection.execute update_pre_order_item_date_sql

      # reload so rails has updated in-memory representation for accurate
      # completeness check
      self.reload

      if pre_order_complete?
        t = Time.current
        self.ordercreatedate = t
        self.order.preordercompletedate = t

        save && order.autocalc_delivered_date!
      end
    end
  end

  def to_s
    "Pre-Order #{preorderid}"
  end

end

app/controllers/pre_orders_controller.rb
class PreOrdersController < ApplicationController
  include DefaultCrudController

  load_and_authorize_resource

  before_action :set_pdf_options, only: [:confirmation]

  button :confirmation, false
  button :confirmation_preview, 'Confirmation'

  button :upload, false
  button :new_items, 'Add or Upload Items'
  button :resend_confirmation, false #'Resend Confirmation Email'

  # submit :order_update, false
  button :create_order, 'Create Order', unless: -> { resource.order.present? },
                                        class: 'btn btn-primary bg-yellow',
                                        data: {
                                          method: :post,
                                          confirm: "Really ready to create the order?"
                                        }


  def confirmation_preview
    render 'preview'
  end

  def new_items
    redirect_to new_pre_order_pre_order_item_path(resource)
  end

  def upload
    svc = PreOrderImportService.for(@pre_order)

    if items = svc.import(params[:file])
      render json: {
        message: "Imported #{items} items to #{@pre_order}",
           href: pre_order_path(@pre_order)
         }
    else
      render plain: 'Error', status: :unprocessable
    end

  rescue => e
    render plain: "Error: #{e.message}", status: :internal_server_error
  end

  def set_pdf_options
    @pdf_options['orientation']  = 'Landscape'
    @pdf_options['margin-left']  = '0.3in'
    @pdf_options['margin-right'] = '0.3in'
  end


  def pre_order_params
    params.require(:pre_order).permit([
      :preorderdate,
      :preorderbatch,
      :custid,
      :preordernotes,
      :preordersh1,
      :preordersh2,
      :preordervendorid,
      :orderid,
      :ordercreatedate,
      :preorderanalysisdate,
      :confirmationdate,
      :preordercheck,
      :notes,
      :ds_tax_amount,
      :splrid,
    ])
  end

end

app/views/pre_orders/_confirmation.html.haml
.content
  %table.table.table-sm.m-0.table-borderles
    %tr
      %td.wpc30(rowspan=2)
        = render OfficeAddressComponent.new
        %p
        %strong TO:
        = @pre_order.customer.full_name
        %br
        = @pre_order.customer.custbusinessname
        %br
        = @pre_order.customer.custaddress
        %br
        = @pre_order.customer.city_state_zip

      %td.wpc25
        =logo_image(height: '80px')
      %td.text-center
        %h1.display-3
          %u Order Confirmation
      %td.w-25.text-right
        Report Date: #{Date.today}
        %br
        Order Date: #{@pre_order.preorderdate.to_date}
    %tr
      %td.w-25.text-right

      %td.w-25
        %p.text-right Order Number:
      %td.w-25.text-right
        %p.text-left
          = @pre_order.preorderbatch
        = @pre_order.order.barcode_data(margin: 0, height: 40, xdim: 2).html_safe
        %br
        =@pre_order.orderid
    %tr
      %td.align-bottom
      %td(colspan=2)
        Order Notes:
        %br
        = @pre_order.preordernotes
      %td

  %table.table.table-striped.table-sm.table-bordered
    %thead
      %th.border.border-dark Qty
      %th.border.border-dark UoM
      %th.border.border-dark ID#
      %th.border.border-dark Manf
      %th.border.border-dark Item #
      %th.border.border-dark Desc
      %th.border.border-dark Price Per
      %th.border.border-dark Price Total
    %tbody
      - @pre_order.items.for_confirmation.each do |item|
        %tr
          %td=item.orderquant2
          %td=item.sku2.skuminunitstype
          %td=item.sku2.skuid
          %td=item.sku2.manf
          %td=item.sku2.itemno
          %td=item.sku2.skudesc
          %td=item.orderpriceper2
          %td=item.orderpricetotal2

  %table.table.table-sm.table-borderless
    %tr
      %td.wpc20.align-top
        #{@pre_order.items.for_confirmation.size} SKUs Total
      %td
      %td.wpc20
        .callout.callout-info
          %table.table
            %tr
              %th.text-right Subtotal
              %td.text-right=number_to_currency(@pre_order.ordersubtotal)
            %tr
              %th.text-right S and H
              %td.text-right 0
            %tr
              %th.text-right Sales Tax
              %td.text-right=number_to_currency(@pre_order.ordertaxtotal)
            %tr
              %th.text-right TOTAL
              %td.text-right=number_to_currency(@pre_order.orderpricetotal)

app/views/pre_orders/_form.html.haml
.content
  = default_resource_form(read_only: local_assigns[:readonly], wrapper: :vertical_form) do |f|
    .row
      .col-12
        .card.card-primary.card-outline.card-outline-tabs
          .card-header.p-0.border-bottom-0
            %ul#tab.nav.nav-tabs{:role => "tablist"}
              %li.nav-item
                %a#general-tab.nav-link.active{"aria-controls" => "general", "aria-selected" => "true", "data-toggle" => "pill", :href => "#general", :role => "tab"} General
              %li.nav-item
                %a#drop-ship-tab.nav-link{"aria-controls" => "general", "aria-selected" => "true", "data-toggle" => "pill", :href => "#drop-ship", :role => "tab"} Drop Ship
              %li.nav-item
                %a#notes-tab.nav-link{"aria-controls" => "notes", "aria-selected" => "false", "data-toggle" => "pill", :href => "#notes", :role => "tab"}
                  Notes
                  - if @resource.notes.present?
                    %span.float-right.badge.bg-info=fa_icon 'asterisk'
          .card-body
            #tabContent.tab-content
              #general.tab-pane.fade.active.show{"aria-labelledby" => "general-tab", :role => "tabpanel"}
                - if @pre_order.customer.present?
                  .row
                    .col-12
                      = render partial: 'customers/billing_mode', locals: { customer: @pre_order.customer }
                .row
                  .col-3
                    = f.input :preorderbatch, wrapper: :vertical_form, disabled: true
                    = f.input :preorderdate,  wrapper: :vertical_form
                  .col-3
                    = f.association :customer, wrapper: :vertical_form
                    = f.association :vendor,   wrapper: :vertical_form
                  .col-3
                    = f.input :preorderanalysisdate, wrapper: :vertical_form
                    = f.input :confirmationdate, wrapper: :vertical_form
                  .col-3
                    .row
                      .col-9
                        = f.input :ordercreatedate, wrapper: :vertical_form
                      .col-3
                        - if @pre_order.order.present?
                          = link_to order_path(@pre_order.order), class: 'btn btn-outline-secondary', target: :blank do
                            = fa_icon 'external-link-alt', text: "Go to Order #{@pre_order.orderid}", right: true
                    = f.input :preordercheck, wrapper: :vertical_form
              #drop-ship.tab-pane.fade{"aria-labelledby" => "drop-ship-tab", :role => "tabpanel"}
                .row
                  .col-4
                    = f.input :ds_tax_amount, as: :currency
                    = f.association :supplier, hint: 'Drop ship order paid by'
              #notes.tab-pane.fade{"aria-labelledby" => "notes-tab", :role => "tabpanel"}
                = f.input :notes, wrapper: :vertical_form

        - if action_name == 'show'
          .card.card-primary-card-outline
            .card-header
              %h2.card-title PreOrder Items (#{@pre_order.items.count})
              .card-tools
                %a.btn.btn-tool{href: new_pre_order_pre_order_item_path(@pre_order)}
                  = fa_icon 'plus'
                  Add Item

            .card.body
              = render_datatable PreOrderItemsDatatable.new(pre_order: @pre_order),
                buttons:    false,
                charts:     false,
                entries:    false,
                filters:    false,
                inline:     false,
                namespace:  nil,
                pagination: false,
                search:     false,
                simple:     false,
                sort:       false

    - unless local_assigns[:readonly]
      .row
        = simple_form_submit(f)

- content_for :scripts do
  = javascript_include_tag 'pre_order_items_datatable'

app/views/pre_orders/_form_create.html.haml
= render partial: 'form'

app/views/pre_orders/confirmation.html.haml
- content_for :page_title do
  =@page_title

=render partial: 'confirmation'